services:
  # The Database Service
  db:
    image: postgres
    container_name: my-postgres-db
    environment:
      POSTGRES_USER: razbas
      POSTGRES_PASSWORD: razbas
      POSTGRES_DB: Zdocker
    ports:
      - "5432:5432"

  # The Spring Boot App Service
  app:
    build: .
    container_name: my-running-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Zdocker
      SPRING_DATASOURCE_USERNAME: razbas
      SPRING_DATASOURCE_PASSWORD: razbas
    depends_on:
      - db