apiVersion: apps/v1
kind: Deployment
metadata:
  name: zdocker-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zdocker-app
  template:
    metadata:
      labels:
        app: zdocker-app
    spec:
      containers:
        - name: zdocker-container
          image: sabzar123/zdocker-app:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          # ADD THIS SECTION BELOW
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/Zdocker
            - name: SPRING_DATASOURCE_USERNAME
              value: razbas
            - name: SPRING_DATASOURCE_PASSWORD
              value: razbas