apiVersion: v1
kind: Service
metadata:
  name: zdocker-app
spec:
  type: NodePort
  selector:
    app: zdocker-app  # <--- Change this to match your Pod labels
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007